catching up all local changes

diff --git a/helm/Makefile b/helm/Makefile
--- a/helm/Makefile
+++ b/helm/Makefile
@@ -7,26 +7,48 @@ SHELL=/bin/bash
 # HELP
 # This will output the help for each task
 # thanks to https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
-.PHONY: help
+.PHONY: help build
 
 help: ## This help.
 	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
 
-.DEFA
+.DEFAULT_GOAL := help
 
-AULT_GOAL := help
+BUCKET_MASTER="gs://static.up9.io/helm/"
+BUCKET_DEVELOP="gs://static.up9.io/helm-develop/"
+BUCKET:=${BUCKET_DEVELOP}
 
-BUCKET_MASTER=gs://static.up9.com/helm/
-BUCKET_DEVELOP=www.up9.io
-#ENV=${ENV_PROD}
-ENV:=${ENV_PREVIEW}
+CPLOG="/tmp/cp.$$$$.log"
+
+CHARTNAME="up9agent"
 
 clean:	## remove build artifacts
-	@echo Cleaning files .. 
-	@ls -l *.tgz index.yaml
+	@echo Cleaning files: 
+	@(ls -l ./build 2>/dev/null || echo "")
+	@rm -rf build
+	@echo Done.
 
-build:  ## Deploy all services to Kubernetes cluster
-	@kubectl -n trdemo get svc,pods,deploy -o wide
 
-publish:  ## Run all services as dockers
+build:  test ## build Helm repo artifacts
+	mkdir -p ./build
+	cd build && helm package ../up9 && helm repo index . && ls -l
+
+publish:  publish-develop ## publish Helm chart - copy to public bucket
+
+publish-develop:	build 	## publish Helm chart to DEVELOP repo - https://static.up9.com/helm-develop
+	@cd build && gsutil cp -c -L $(CPLOG) -r . $(BUCKET_DEVELOP) ; \
+		echo -e "\nSee operation log in ${C_Y} ${CPLOG} ${C_N}"
+
+
+publish-master:		build 	## publish Helm chart to MASTER repo - https://static.up9.com/helm
+	@cd build && gsutil cp -c -L /tmp/cp.$$.log -r . $(BUCKET_MASTER) 	
+
+test: ## test bucket connection and tooling
+	@echo -e "Verifying connection and tooling\n"
+	@(gsutil ls ${BUCKET} 2>/dev/null && \
+		echo -e "\n ${C_C} Succefully accessed bucket ${C_Y} ${BUCKET} ${C_N}") \
+	|| (echo -e "\n ${C_R} Failed ${C_N} to access bucket ${C_Y} ${BUCKET} ${C_N}! ")
+	@(helm version | grep -o v3 >/dev/null && echo -e "  Will use ${C_Y} helm ${C_N} for build" ) \
+		|| (echo -e "\n ${C_R} Incompatible or missing ${C_Y} helm ${C_N} -- cannot build! ")
+	@echo ""
 
